version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin

  node-dev:
    build:
      context: ./api
      dockerfile: ./dockerfile
    tty: true
    ports:
      - "3002:3002"
    volumes:
      - ./api:/app

  react-dev:
    build:
      context: ./client
      dockerfile: ./dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

